### ISSUE TITLE
Adding Examples to the NerKor annotation guide

### ISSUE THREAD

**Issue by zsofiar** [nytud/NYTK-NerKor#12]
The RC2S2 research group is working on a NER annotation project and has used the [annotation guidelines documentation](https://github.com/nytud/NYTK-NerKor/blob/main/guidelines/NerKor_annotation_guidelines.pdf) prepared for this repository. As a representative of the research group, I would like to provide feedback, ask some questions and add some suggestions and examples that could be useful to be added to the document. 

**Feedback**

Thanks for the useful guidelines, it helped the research group to understand the main principles of the NER annotation. The examples prepared in the documentation are easy to understand and helpful.

**Questions**

1. How would you annotate the expressions that are grammatically attached together? Examples: "Német-, Olasz- és Franciaország" or "Kun és a Népszínház utca". In some software, such as in Label Studio, it is not possible to annotate the corresponding parts correctly, the available options are:

- to annotate the example together as a whole, or 
- to annotate not full phases ("Német-", "Olasz-" etc.). 

2. How would you annotate the phrase "Jóisten" in the following: “de a Jóisten tudja, miért, …”? It is written in the guide a biblical person is to be annotated as a person. Does that stand for the above example as well? 

**Suggestions and examples**

It would be great the elaborate the cases of NE-s and their attachments (formed in Hungarian rather as tulajdonnévi és köznévi tagok viszonya) in more detail. Examples: 1) "Airbnb-szolgáltatás", 2) "BKV-ellenőr",  3) "NATO-szövetségesei", 4) "a festő Balaton-korszakát" ("Balaton-korszak" is meant as an art era of a painter), 5) "Nabucco gázvezeték". The annotation rules to be applied could be different in some of the above examples. A couple of further examples in the guide and a detailed explanation could be useful to understand the different cases that could come up.

Further examples to the MISC category would be useful. The MISC category could be improved with further description and completed with the names of trade routes, gas pipelines etc. such as: "Selyemút", "Déli Áramlat", "Nabucco gázvezeték", or with names of radio stations: "MusicFM", "InfóRádió" etc. Of course only if the above examples are categorized correctly.

**Comment by esztersimon** [comment]
Thanks for using our guidelines, and also thanks for your comments and suggestions! We will update the guidelines with some of your examples. Please refer to our newly published paper if you publish your results!

Answers to your questions:

1. In your example "Kun és a Népszínház utca", the names of the two streets are annotated separately. Yes, they are not full phrases... 
2. If you refer to God as a person, it should be annotated as PER. But if it is just used as a damn or swear, it is not annotated as a name. 

Comments on your suggestions:

The first 4 of your examples are not to be annotated as NEs. Their head is a common noun, thus they are common nouns. However, your 5. example ("Nabucco gázvezeték"), "Nabucco" is a MISC, while "gázvezeték" is a simple common noun, not to be annotated. 

Names of trade routes and gas pipelines are to be annotated as MISC. However, radio stations can be annotated as ORG as well if the name refers to the company or as PER if it refers to a team of people.
