### ISSUE TITLE
Duplicates in dataset

### ISSUE THREAD

**Issue by AngledLuffa** [nytud/NYTK-NerKor#13]
Another minor issue: there are some duplicates in the dataset.  For example,

```
('-', 'Micsoda', '?')
('-', 'Loder', '!')
('-', 'Chilcote', '!')
```

and a bunch of others.  I can automate removal of those if it's helpful

**Comment by esztersimon** [comment]
Don't remove these, since they are organic parts of a novel. Yes, there are "duplicates" in the language we use. For example, I can type a sentence twice. Yes. The language is redundant. Yes.
