### ISSUE TITLE
Rákos-patak, Napos-part, Tory-párt

### ISSUE THREAD

**Issue by tamvar** [nytud/NYTK-NerKor#4]
A három kifejezésből a Tory-párt megítélése a kérdéses, amely szerintem névkifejezés, ahogy ezt egy pull request-ben jeleztem, Eszter szerint 

"Tory-párt':` it is a word composition, whose head is a simple noun, therefore the whole composition is a noun, not a proper noun." 

A helyzet ennél egyszerübb: akárhogyan is van magyar helyesírásilag írva, a szövegben előforduló kifejezés "a Tory-párt" az angol Konzervatív Pártra unikálisan referáló névkifejezés, valójában a Konzervatív Párt informális neve. Angolul Tory Party.

Egyébént már csak a Konzervatív Párt, Liberális Párt stb. kedvéért átgondolásra szorul az annotálási útmutató 3.3.2 pontja, amelyik csak a helynevekre vonatkoztatva tárgyalja a köznévű fejtaggal rendelkező kifejezéseket, holott a 3.2-ben bőven van olyen szervezetnév is, amelyeknek a feje köznév pl. múzeum, egyesület stb. -- többek között a "párt" szó is ilyen. 

A fent idézett indoklás tehát túlzottan általánosít, amint ezt az annotálási útutató fenti pontjai is mutatják. Nem véletlen, hogy ílyen általános érvénnyel nem is található meg az útmutatóban. Ha pedig a "párt" szó köznévként is széles körben névalkotó elem, és a névkifejezés unikális (v.ö. pl. "a Tory-párt" vs. "a Tory szavazó"), akkor nem látok még formális okot sem, hogy a _Tory-párt_-ot ne tekintsük névkifejezésnek.

**Comment by esztersimon** [comment]
Az annotációs útmutató 3.3.2. pontja csupa olyan eseteket tartalmaz, amikor köznévi utótag járul egy tulajdonnévi elemhez, pl. 'Duna folyó'. Ez nem szóösszetétel, hanem két külön szó, amelyek közül az egyik név, a másik pedig nem a név része. Vagyis az útmutatónak ez a pontja nem tartozik ide. 

A 3.2-ben már tényleg hasonló példák szerepelnek, de az ott felsoroltakra mind igaz az, hogy azoknak az a hivatalos nevük, pl. 'Magyar Nemzeti Bank'. Ebben az esetben fel sem merül annak a lehetősége, hogy a 'Bank' ne tartozna a névhez, hiszen annak hivatalosan és írásképileg is a része. Vagyis ez a pont sem érvényes az itt vizsgált esetre. 

Az említett szöveg egy régies szépirodalmi szöveg, amelyben a szerző nem a mai helyesírási szabályokat követi. A mai szabályok szerint ezt úgy kellene írni, hogy 'tory párt', merthogy ez nem a hivatalos neve a pártnak, hanem a hétköznapi elnevezése. Ugyanolyan, mintha magyarul azt írnánk, hogy a 'kereszténydemokrata párt'. Annak se ez a neve, hanem ez egy köznévi frázis, amellyel ugyan egy egyedi entitásra hivatkozunk, de az, amivel hivatkozunk rá, nem egyedi. A szerző által itt alkalmazott írásmód az angolszász hagyományt követi, amely a politikai és a felekezeti hovatartozást is nagybetűvel írja, de ettől még a magyar szövegekben ez nem tekinthető névnek.
